/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.prototipogym;

import java.nio.file.Files;
import java.nio.file.Paths;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Locale;
import java.util.Set;
import javax.swing.JOptionPane;

/**
 *
 * @author asist-depti
 */
public class PACuota extends javax.swing.JFrame {

    /**
     * Creates new form PACuota
     */
    public PACuota() {
        initComponents();
        setTitle("Pantera Fitness");
        setLocationRelativeTo(null);
        // Establecer fecha de inicio: 1 de abril de 2025
        Calendar inicio = Calendar.getInstance();
        inicio.set(2025, Calendar.APRIL, 1); // Recuerda: los meses empiezan desde 0 (enero = 0)
        fechainicioChooser.setDate(inicio.getTime());

        // Establecer fecha final: 30 de abril de 2025
        Calendar fin = Calendar.getInstance();
        fin.set(2025, Calendar.APRIL, 30);
        fechafinalChooser.setDate(fin.getTime());
    }
    
    private void procesarCobros() {
    try {
        Date fechaInicio = fechainicioChooser.getDate();
        Date fechaFinal = fechafinalChooser.getDate();
        SimpleDateFormat sdf = new SimpleDateFormat("dd MMM yyyy", new Locale("es", "ES"));

        // Cargar las líneas del detalle y extraer Id_Cobro_Cuota de los que están marcados como true
        List<String> lineasDetalle = Files.readAllLines(Paths.get("archivos/detalle_cuota.txt"));
        List<String> nuevasLineasDetalle = new ArrayList<>();
        Set<String> cobrosPagados = new HashSet<>();

        for (String linea : lineasDetalle) {
            String[] partes = linea.split(",");
            if (partes.length >= 6 && partes[5].equalsIgnoreCase("true")) {
                cobrosPagados.add(partes[4]); // Id_Cobro_Cuota
            }
        }

        // Leer y actualizar cobro.txt
        List<String> lineasCobro = Files.readAllLines(Paths.get("archivos/cobro.txt"));
        List<String> nuevasLineasCobro = new ArrayList<>();

        for (String linea : lineasCobro) {
            String[] partes = linea.split(",");
            if (partes.length >= 6) {
                String idCobro = partes[0];
                Date fechaCobro = sdf.parse(partes[1]);

                // Si el cobro es uno de los pagados y está en el rango, se marca como true
                if (cobrosPagados.contains(idCobro) &&
                        !fechaCobro.before(fechaInicio) &&
                        !fechaCobro.after(fechaFinal)) {
                    partes[5] = "true";
                }

                nuevasLineasCobro.add(String.join(",", partes));
            } else {
                nuevasLineasCobro.add(linea);
            }
        }

        // Actualizar detalle_cuota.txt para marcar como Procesado
        for (String linea : lineasDetalle) {
            String[] partes = linea.split(",");
            if (partes.length >= 6 && partes[5].equalsIgnoreCase("true")) {
                String idCobro = partes[4];
                if (cobrosPagados.contains(idCobro)) {
                    partes[5] = "Procesado";
                }
                nuevasLineasDetalle.add(String.join(",", partes));
            } else {
                nuevasLineasDetalle.add(linea);
            }
        }

        // Guardar los archivos actualizados
        Files.write(Paths.get("archivos/cobro.txt"), nuevasLineasCobro);
        Files.write(Paths.get("archivos/detalle_cuota.txt"), nuevasLineasDetalle);

        JOptionPane.showMessageDialog(this, "Cobros procesados correctamente.");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al procesar cobros: " + e.getMessage());
        e.printStackTrace();
    }

}

    
    private void cancelar() {
            this.dispose();  
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fechainicioChooser = new com.toedter.calendar.JDateChooser();
        fechafinalChooser = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        btnprocesar = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Actualizar Cobro");

        btnprocesar.setText("Procesar");
        btnprocesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprocesarActionPerformed(evt);
            }
        });

        btnsalir.setText("Volver");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(btnprocesar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addComponent(btnsalir)
                .addGap(69, 69, 69))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fechainicioChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fechafinalChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addComponent(fechainicioChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(fechafinalChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnprocesar)
                    .addComponent(btnsalir))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        cancelar();
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btnprocesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprocesarActionPerformed
         procesarCobros();
    }//GEN-LAST:event_btnprocesarActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PACuota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PACuota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PACuota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PACuota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PACuota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnprocesar;
    private javax.swing.JButton btnsalir;
    private com.toedter.calendar.JDateChooser fechafinalChooser;
    private com.toedter.calendar.JDateChooser fechainicioChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
